---
- hosts: localhost
  become: True
  tasks:
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"

    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True

    - name: Creates website under /var/www directory
      file:
        path: "{{ item }}"
        state: directory
        owner: apache
        group: apache
      with_items:
        - /var/www/website1.com/public_html/
        - /var/www/website2.com/public_html/
        - /var/www/website3.com/public_html/
    
    - name: Copy website files to /var/www/website/public_html/
      copy:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
      with_items:
        - { src: 'website1.com/public_html/index.html', dest: '/var/www/website1.com/public_html/'} 
        - { src: 'website2.com/public_html/index.html', dest: '/var/www/website2.com/public_html/'}
        - { src: 'website3.com/public_html/index.html', dest: '/var/www/website2.com/public_html/'}
    
    - name: Copy apache configuration files to conf.d
      copy:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
      with_items:
          - {src: 'confd/website1.com.conf', dest: '/etc/httpd/conf.d/'}
          - {src: 'confd/website2.com.conf', dest: '/etc/httpd/conf.d/'}          
          - {src: 'confd/website3.com.conf', dest: '/etc/httpd/conf.d/'}          
...
